### ISSUE TITLE
Consider using Seeed_Arduino_rpcWiFiManager for Wi-Fi/Azure IoT configuration

### ISSUE THREAD

**Issue by kartben** [SeeedJP/wioterminal-iotpnp-device#1]
In addition to having the option to setup ssid, iotc credentials etc. over the serial console, it would be nice to use https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFiManager to have a setup experience that can be done entirely from a web browser/mobile phone. 

What do you think?

**Comment by matsujirushi** [comment]
Hi @matsujirushi ,
Thanks for issue.
I opened the GitHub Discussions and post it.
https://github.com/SeeedJP/wioterminal-iotpnp-device/discussions/2

**Comment by matsujirushi** [comment]
https://github.com/SeeedJP/wioterminal-iotpnp-device/discussions/2#discussioncomment-691324
